// <auto-generated />
namespace DoSoft.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _0712 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0712));
        
        string IMigrationMetadata.Id
        {
            get { return "201807121344226_0712"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
